const state={images:[],imageEls:[],animations:[],targets:[],gridPositions:[],options:{word:"2025",fontSize:200,cellSize:48,speed:1200,stagger:120,randomOrder:true},running:false,stage:null,info:null,maskCanvas:null,stageSize:{w:0,h:0},mode:"idle",lastClickedEl:null,sequenceRunning:false};
function q(id){return document.getElementById(id)}
function setInfo(t){state.info.textContent=t}
function init(){state.stage=q("stage");state.info=q("info");state.maskCanvas=q("maskCanvas");q("word").addEventListener("input",e=>state.options.word=e.target.value);q("speed").addEventListener("input",e=>state.options.speed=clamp(+e.target.value,300,3000));q("stagger").addEventListener("input",e=>state.options.stagger=clamp(+e.target.value,40,600));q("randomOrder").addEventListener("change",e=>state.options.randomOrder=!!e.target.checked);q("files").addEventListener("change",handleFiles);q("demo").addEventListener("click",fillDemo);q("start").addEventListener("click",start);q("pause").addEventListener("click",pause);q("resume").addEventListener("click",resume);q("replay").addEventListener("click",replay);window.addEventListener("resize",onResize);onResize();setInfo("准备就绪")}
function clamp(n,min,max){return Math.max(min,Math.min(max,n))}
function onResize(){const r=state.stage.getBoundingClientRect();state.stageSize.w=r.width;state.stageSize.h=r.height;state.stage.style.width="100%";state.stage.style.height="100%"}
async function handleFiles(e){const files=[...(e.target.files||[])].slice(0,500);if(!files.length){setInfo("未选择图片");return}setInfo("读取图片中");const urls=await Promise.all(files.map(readFile));state.images=urls;setInfo(`已载入 ${urls.length} 张图片`)}
function readFile(file){return new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(fr.result);fr.onerror=e=>rej(e);fr.readAsDataURL(file)})}
function fillDemo(){const colors=["#e74c3c","#8e44ad","#3498db","#1abc9c","#f1c40f","#e67e22","#2ecc71","#16a085","#2c3e50","#d35400"];const size=512;const n=30;const list=[];for(let i=0;i<n;i++){const c=colors[i%colors.length];const canvas=document.createElement("canvas");canvas.width=size;canvas.height=size;const ctx=canvas.getContext("2d");ctx.fillStyle=c;ctx.fillRect(0,0,size,size);ctx.fillStyle="#ffffff";ctx.font=`bold ${size*0.5}px sans-serif`;ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(String(i+1),size/2,size/2);list.push(canvas.toDataURL("image/png"))}state.images=list;setInfo(`已生成演示图片 ${n} 张（高分辨率）`)}
function clearStage(){state.animations.forEach(a=>{try{a.cancel()}catch{}});state.animations=[];state.imageEls.forEach(el=>el.remove());state.imageEls=[];state.targets=[]}
function renderMask(word,fontSize){const c=state.maskCanvas;const ctx=c.getContext("2d");const stageW=state.stageSize.w||800;const stageH=state.stageSize.h||600;c.width=stageW;c.height=stageH;ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle="#000000";ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle="#ffffff";ctx.textAlign="center";ctx.textBaseline="middle";ctx.font=`300 ${fontSize}px Noto Sans SC, sans-serif`;ctx.fillText(word,c.width/2,c.height/2);ctx.lineWidth=Math.max(1,Math.floor(fontSize*0.03));ctx.strokeStyle="#ffffff";ctx.strokeText(word,c.width/2,c.height/2);const img=ctx.getImageData(0,0,c.width,c.height);const id=img.data;let minX=c.width,minY=c.height,maxX=0,maxY=0;for(let y=0;y<c.height;y++){const off=y*c.width*4;for(let x=0;x<c.width;x++){const idx=off+x*4;if(id[idx+3]>16&&((id[idx]+id[idx+1]+id[idx+2])/3)>20){if(x<minX)minX=x;if(y<minY)minY=y;if(x>maxX)maxX=x;if(y>maxY)maxY=y}}}if(minX>maxX||minY>maxY){return {data:img,width:c.width,height:c.height,rect:{x:0,y:0,w:0,h:0}}}const rect={x:Math.max(0,minX-2),y:Math.max(0,minY-2),w:Math.min(c.width,maxX+2)-Math.max(0,minX-2),h:Math.min(c.height,maxY+2)-Math.max(0,minY-2)};return {data:img,width:c.width,height:c.height,rect}
}
function measureCharWidth(ch,size){const t=document.createElement("canvas");t.width=Math.ceil(size*2);t.height=Math.ceil(size*2);const ctx=t.getContext("2d");ctx.fillStyle="#000";ctx.fillRect(0,0,t.width,t.height);ctx.fillStyle="#fff";ctx.textAlign="center";ctx.textBaseline="middle";ctx.font=`300 ${size}px Noto Sans SC, sans-serif`;ctx.fillText(ch,t.width/2,t.height/2);ctx.lineWidth=Math.max(1,Math.floor(size*0.03));ctx.strokeStyle="#fff";ctx.strokeText(ch,t.width/2,t.height/2);const img=ctx.getImageData(0,0,t.width,t.height).data;let minX=t.width,maxX=0;for(let y=0;y<t.height;y++){const off=y*t.width*4;for(let x=0;x<t.width;x++){const idx=off+x*4;if(img[idx+3]>16&&((img[idx]+img[idx+1]+img[idx+2])/3)>20){if(x<minX)minX=x;if(x>maxX)maxX=x}}}if(minX>maxX)return Math.floor(size*0.5);return Math.max(1,(maxX-minX+1))}
function renderMaskAuto(word){const c=state.maskCanvas;const ctx=c.getContext("2d");const stageW=state.stageSize.w||800;const stageH=state.stageSize.h||600;c.width=stageW;c.height=stageH;let fs=Math.floor(Math.min(stageW,stageH)*0.28);const pad=Math.floor(Math.min(stageW,stageH)*0.06);const targetW=stageW-2*pad;const targetH=stageH-2*pad;let tries=0;while(tries<10){const widths=[];for(const ch of word){widths.push(measureCharWidth(ch,fs))}const csCandidate=Math.max(16,Math.floor(fs/20));const gap=Math.max(2,Math.floor(csCandidate*0.35));const total=widths.reduce((a,b)=>a+b,0)+gap*(Math.max(0,word.length-1));const height=fs;if(total>targetW||height>targetH){fs=Math.max(24,Math.floor(fs*0.9));tries++;continue}if(total<targetW*0.5&&height<targetH*0.7){fs=Math.floor(fs*1.1);tries++;continue}break}state.options.fontSize=fs;state.options.cellSize=Math.max(16,Math.floor(fs/20));ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle="#000";ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle="#fff";ctx.textAlign="left";ctx.textBaseline="middle";ctx.font=`300 ${fs}px Noto Sans SC, sans-serif`;const widths2=[];for(const ch of word){widths2.push(measureCharWidth(ch,fs))}const gap2=Math.max(2,Math.floor(state.options.cellSize*0.35));const total2=widths2.reduce((a,b)=>a+b,0)+gap2*(Math.max(0,word.length-1));let x0=Math.round((stageW-total2)/2);const y0=Math.round(stageH/2);for(let i=0;i<word.length;i++){const ch=word[i];ctx.fillText(ch,x0,y0);ctx.lineWidth=Math.max(1,Math.floor(fs*0.03));ctx.strokeStyle="#fff";ctx.strokeText(ch,x0,y0);x0+=widths2[i]+gap2}const img=ctx.getImageData(0,0,c.width,c.height);const id=img.data;let minX=c.width,minY=c.height,maxX=0,maxY=0;for(let y=0;y<c.height;y++){const off=y*c.width*4;for(let x=0;x<c.width;x++){const idx=off+x*4;if(id[idx+3]>16&&((id[idx]+id[idx+1]+id[idx+2])/3)>20){if(x<minX)minX=x;if(y<minY)minY=y;if(x>maxX)maxX=x;if(y>maxY)maxY=y}}}if(minX>maxX||minY>maxY){return {data:img,width:c.width,height:c.height,rect:{x:0,y:0,w:0,h:0}}}const rect={x:Math.max(0,minX-2),y:Math.max(0,minY-2),w:Math.min(c.width,maxX+2)-Math.max(0,minX-2),h:Math.min(c.height,maxY+2)-Math.max(0,minY-2)};return {data:img,width:c.width,height:c.height,rect}
}
function computeTargets(mask,cell){const w=mask.width,h=mask.height;const r=mask.rect;const arr=[];const id=mask.data.data;const step=cell;const ss=Math.max(1,Math.floor(cell/4));for(let gy=r.y;gy<r.y+r.h;gy+=step){for(let gx=r.x;gx<r.x+r.w;gx+=step){let hits=0,total=0;for(let y=gy;y<Math.min(gy+step,r.y+r.h);y+=ss){for(let x=gx;x<Math.min(gx+step,r.x+r.w);x+=ss){const idx=(y*w+x)*4;const a=id[idx+3];const b=(id[idx]+id[idx+1]+id[idx+2])/3;if(a>64&&b>180){hits++}total++}}const ratio=hits/Math.max(1,total);if(ratio>=0.35){arr.push({x:Math.round(gx),y:Math.round(gy)})}}}return arr}
function pickTargets(all,count){if(all.length<=count)return all;const step=Math.max(1,Math.floor(all.length/count));const pick=[];for(let i=0;i<all.length;i+=step){pick.push(all[i]);if(pick.length>=count)break}return shuffle(pick)}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function createImageEls(heroSize,seq){clearStage();seq.forEach(src=>{const el=document.createElement("div");el.className="photo";el.style.width=heroSize+"px";el.style.height=heroSize+"px";const img=document.createElement("img");img.loading="eager";img.decoding="async";img.src=src;el.appendChild(img);state.stage.appendChild(el);state.imageEls.push(el)});setInfo(`已创建元素 ${state.imageEls.length}`)}
function computeGrid(n){const r=state.stage.getBoundingClientRect();const W=r.width,H=r.height;let cols=Math.ceil(Math.sqrt(n*W/H));let rows=Math.ceil(n/cols);let cell=Math.floor(Math.min(W/cols,H/rows));cell=Math.max(24,cell);const gap=Math.max(8,Math.floor(cell*0.08));const totalW=cols*cell+(cols-1)*gap;const totalH=rows*cell+(rows-1)*gap;const x0=Math.round((W-totalW)/2);const y0=Math.round((H-totalH)/2);const pos=[];let i=0;for(let ry=0;ry<rows;ry++){for(let cx=0;cx<cols;cx++){if(i>=n)break;const x=x0+cx*(cell+gap);const y=y0+ry*(cell+gap);pos.push({x,y});i++}}return {positions:pos,cell,gap}}
function placeGrid(grid,animate=false,duration=1200){const hero=Math.floor(Math.sqrt((state.stageSize.w*state.stageSize.h)/9));const scale=Math.max(0.1,grid.cell/hero);state.gridPositions=grid.positions;const centerX=Math.round((state.stageSize.w-hero)/2);const centerY=Math.round((state.stageSize.h-hero)/2);if(animate){state.stage.style.pointerEvents="none";setInfo("入场动画播放中")}state.imageEls.forEach((el,i)=>{const p=grid.positions[i];el.dataset.baseScale=String(scale);if(animate){const from=`translate3d(${centerX}px,${centerY}px,0) scale(0.2)`;const to=`translate3d(${p.x}px,${p.y}px,0) scale(${scale})`;el.style.transform=from;el.style.opacity=0;const a=el.animate([{transform:from,opacity:0},{transform:to,opacity:1}],{duration:duration,easing:"cubic-bezier(0.2, 0.8, 0.2, 1)",fill:"forwards"});a.onfinish=()=>{el.style.transform=to;el.style.opacity=1};state.animations.push(a);el.style.zIndex="1";}else{el.style.transform=`translate3d(${p.x}px,${p.y}px,0) scale(${scale})`;el.style.opacity=1;el.style.zIndex="1";}bindHover(el,scale)});if(animate){setTimeout(()=>{state.stage.style.pointerEvents="auto";state.mode="grid";setInfo(`网格展示：${state.imageEls.length} 张，单元 ${grid.cell}px`)},duration)}else{state.mode="grid";setInfo(`网格展示：${state.imageEls.length} 张，单元 ${grid.cell}px`)} }
function bindHover(el,baseScale){let enlarged=false;let highlighted=false;const dur=220;function toScale(s){try{const from=el.style.transform||"";const to=from.includes("scale(")?from.replace(/scale\([^\)]*\)/,`scale(${s})`):`${from} scale(${s})`;const a=el.animate([{transform:from},{transform:to}],{duration:dur,easing:"cubic-bezier(0.22, 1, 0.36, 1)",fill:"forwards"});a.onfinish=()=>{el.style.transform=to};state.animations.push(a)}catch{} }
el.addEventListener("mouseenter",()=>{if(state.mode!=="grid"&&state.mode!=="text")return;highlighted=true;el.style.zIndex="10";el.style.boxShadow=`0 0 0 3px #ff9f43`;toScale(1);enlarged=true});
el.addEventListener("mouseleave",()=>{if(state.mode!=="grid"&&state.mode!=="text")return;el.style.boxShadow="none";el.style.zIndex="1";const from=el.style.transform||"";const back=from.includes("scale(")?from.replace(/scale\([^\)]*\)/,`scale(${baseScale})`):`${from} scale(${baseScale})`;try{const a=el.animate([{transform:from},{transform:back}],{duration:dur,easing:"cubic-bezier(0.22, 1, 0.36, 1)",fill:"forwards"});a.onfinish=()=>{el.style.transform=back};state.animations.push(a)}catch{}enlarged=false;highlighted=false})
}
function layout(word){const {cellSize}=state.options;const mask=renderMaskAuto(word);if(!mask.rect.w||!mask.rect.h){setInfo("字形不可见，请调整词语或参数");return[]}let targets=computeTargets(mask,cellSize);if(!targets.length){setInfo("字形采样过稀，请减小格子大小");return[]}setInfo(`检测到格子 ${targets.length}`);return targets}
function sequenceAnimate(targets,durationMs){const cell=state.options.cellSize;const hero=Math.floor(Math.sqrt((state.stageSize.w*state.stageSize.h)/9));const scale=Math.max(0.1,cell/hero);const dur=durationMs!=null?durationMs:state.options.speed;const count=Math.min(state.imageEls.length,targets.length);state.stage.style.pointerEvents="none";const imgs=[...state.imageEls];if(state.lastClickedEl){const idx=imgs.indexOf(state.lastClickedEl);if(idx>0){imgs.splice(idx,1);imgs.unshift(state.lastClickedEl)}state.lastClickedEl=null}for(let i=0;i<count;i++){const el=imgs[i];el.dataset.baseScale=String(scale);const target=targets[i];const from=el.style.transform;const to=`translate3d(${target.x}px,${target.y}px,0) scale(${scale})`;const a=el.animate([{transform:from,opacity:1},{transform:to,opacity:1}],{duration:dur,easing:"cubic-bezier(0.2, 0.8, 0.2, 1)",fill:"forwards"});a.onfinish=()=>{el.style.transform=to;el.style.opacity=1};state.animations.push(a)}for(let i=0;i<imgs.length-count;i++){const el=imgs[count+i];if(!el)break;const centerSize=hero;const centerX=Math.round((state.stageSize.w-centerSize)/2);const centerY=Math.round((state.stageSize.h-centerSize)/2);const to=`translate3d(${centerX}px,${centerY}px,0) scale(${scale})`;el.dataset.baseScale=String(scale);const a=el.animate([{transform:el.style.transform,opacity:1},{transform:to,opacity:0}],{duration:Math.min(600,Math.floor(dur*0.2)),easing:"ease-out",fill:"forwards"});a.onfinish=()=>{el.style.transform=to;el.style.opacity=0};state.animations.push(a)}setTimeout(()=>{state.stage.style.pointerEvents="auto"},dur);state.mode="text";setInfo("飞入文字中")}
function ensureTargets(count){const word=state.options.word;let cs=state.options.cellSize;let mask=renderMaskAuto(word);let targets=computeTargets(mask,cs);let tries=0;while(targets.length<count&&tries<10){cs=Math.max(16,Math.floor(cs*0.85));state.options.cellSize=cs;mask=renderMaskAuto(word);targets=computeTargets(mask,cs);tries++}if(targets.length>count)targets=pickTargets(targets,count);return targets}
function flyToText(){if(state.sequenceRunning)return;const words=splitWords();if(words.length>1){morphWordsSequence(words);return}const mask=renderMaskAuto(state.options.word);let targets=computeTargets(mask,state.options.cellSize);if(!targets.length){setInfo("字形采样不足");return}if(targets.length>state.imageEls.length){const extra=targets.length-state.imageEls.length;const hero=Math.floor(Math.sqrt((state.stageSize.w*state.stageSize.h)/9));for(let i=0;i<extra;i++){const src=state.images[i%state.images.length];const el=document.createElement("div");el.className="photo";el.style.width=hero+"px";el.style.height=hero+"px";const img=document.createElement("img");img.loading="eager";img.decoding="async";img.src=src;el.appendChild(img);state.stage.appendChild(el);state.imageEls.push(el);el.style.transform=`translate3d(${Math.round(state.stageSize.w/2-hero/2)}px,${Math.round(state.stageSize.h/2-hero/2)}px,0) scale(${Math.max(0.1,state.options.cellSize/hero)})`;el.style.opacity=1}}state.sequenceRunning=true;sequenceAnimate(targets,5000);setTimeout(()=>{state.sequenceRunning=false},5050)}
function randomBetween(a,b){return Math.round(a+Math.random()*(b-a))}
function wait(ms){return new Promise(res=>setTimeout(res,ms))}
function splitWords(){return String(state.options.word||"").trim().split(/\s+/).filter(Boolean)}
function getTargetsForWord(word,count){let cs=state.options.cellSize;let mask=renderMaskAuto(word);let targets=computeTargets(mask,cs);let tries=0;while(targets.length<count&&tries<12){cs=Math.max(16,Math.floor(cs*0.85));state.options.cellSize=cs;mask=renderMaskAuto(word);targets=computeTargets(mask,cs);tries++}if(targets.length>count)targets=pickTargets(targets,count);return targets}
function normalizeGridScales(){const jobs=[];state.imageEls.forEach(el=>{const baseScale=parseFloat(el.dataset.baseScale||"1");try{const anims=el.getAnimations?el.getAnimations():[];anims.forEach(a=>{try{a.cancel()}catch{}})}catch{};const from=el.style.transform||"";const to=from.includes("scale(")?from.replace(/scale\([^\)]*\)/,`scale(${baseScale})`):`${from} scale(${baseScale})`;el.style.boxShadow="none";el.style.zIndex="1";if(from===to){el.style.transform=to;return}try{const a=el.animate([{transform:from},{transform:to}],{duration:180,easing:"cubic-bezier(0.22, 1, 0.36, 1)",fill:"forwards"});state.animations.push(a);jobs.push(new Promise(res=>{a.onfinish=()=>{el.style.transform=to;res()};a.oncancel=()=>res()}))}catch{el.style.transform=to}});return Promise.all(jobs).then(()=>wait(20))}
async function morphWordsSequence(words){if(!words.length)return;const duration=3000;const dwell=1000;for(const w of words){let mask=renderMaskAuto(w);let targets=computeTargets(mask,state.options.cellSize);if(targets.length<state.images.length){let tries=0;while(targets.length<state.images.length&&tries<8){state.options.cellSize=Math.max(12,Math.floor(state.options.cellSize*0.85));mask=renderMaskAuto(w);targets=computeTargets(mask,state.options.cellSize);tries++}}if(!targets.length){setInfo(`词语“${w}”采样不足`);continue}ensureActorCount(targets.length);sequenceAnimate(targets,duration);await wait(duration+dwell)}setInfo("词语序列已完成")}
function ensureActorCount(n){if(state.imageEls.length>=n)return;const hero=Math.floor(Math.sqrt((state.stageSize.w*state.stageSize.h)/9));const scale=Math.max(0.1,state.options.cellSize/hero);const centerX=Math.round((state.stageSize.w-hero)/2);const centerY=Math.round((state.stageSize.h-hero)/2);const need=n-state.imageEls.length;for(let i=0;i<need;i++){const src=state.images[(state.imageEls.length+i)%state.images.length];const el=document.createElement("div");el.className="photo";el.style.width=hero+"px";el.style.height=hero+"px";const img=document.createElement("img");img.loading="eager";img.decoding="async";img.src=src;el.appendChild(img);state.stage.appendChild(el);el.style.transform=`translate3d(${centerX}px,${centerY}px,0) scale(${scale})`;el.style.opacity=0;el.dataset.baseScale=String(scale);bindHover(el,scale);state.imageEls.push(el)}}
async function start(){if(!state.images.length){setInfo("请上传或使用演示图片");return}const mask=renderMaskAuto(state.options.word);let targets=computeTargets(mask,state.options.cellSize);if(!targets.length){setInfo("字形采样过稀，请调整参数");return}state.targets=targets;const seq=buildImageSequence(state.images.length);const stageRect=state.stage.getBoundingClientRect();const heroSize=Math.floor(Math.sqrt((stageRect.width*stageRect.height)/9));createImageEls(heroSize,seq);await Promise.all(state.imageEls.map(el=>{const img=el.querySelector("img");return img.decode?img.decode().catch(()=>{}):Promise.resolve()}));const grid=computeGrid(state.imageEls.length);placeGrid(grid,true,3000);state.imageEls.forEach(el=>{el.addEventListener("click",async()=>{if(state.mode!=="grid")return;state.lastClickedEl=el;await normalizeGridScales();const words=splitWords();if(words.length>1){morphWordsSequence(words)}else{flyToText()}})});} 
function buildImageSequence(targetCount){const imgs=state.images;if(!imgs.length)return[];let seq=[];if(imgs.length>=targetCount){const base=state.options.randomOrder?shuffle([...imgs]):[...imgs];seq=base.slice(0,targetCount);}else{const base=state.options.randomOrder?shuffle([...imgs]):[...imgs];const times=Math.floor(targetCount/base.length);const rem=targetCount%base.length;for(let i=0;i<times;i++){seq=seq.concat(base)}seq=seq.concat(base.slice(0,rem));if(state.options.randomOrder)seq=shuffle(seq)}return seq}
function pause(){state.animations.forEach(a=>{try{a.pause()}catch{}});setInfo("已暂停");state.running=false}
function resume(){state.animations.forEach(a=>{try{a.play()}catch{}});setInfo("继续播放");state.running=true}
function replay(){clearStage();start()}
document.addEventListener("DOMContentLoaded",init)
